--- #YAML:1.0
name:                Bundle-Font
version:             0.01
abstract:            a bundle to install Font modules and dependencies
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Kevin W. Henwood <Khen1950fx@aol.com>
